// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7a3GJTDHEUdkjT2NtSMyoQHIYBmO4nvA',
    appId: '1:147266380618:web:fd35a9a3c7a3530bc7d7b3',
    messagingSenderId: '147266380618',
    projectId: 'fir-login-signup-22aa1',
    authDomain: 'fir-login-signup-22aa1.firebaseapp.com',
    storageBucket: 'fir-login-signup-22aa1.appspot.com',
    measurementId: 'G-09WLL74S9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-uDDMvmx6QLSIn_J-5GSGJBpEAEMqWxo',
    appId: '1:147266380618:android:f065dcab2245ad51c7d7b3',
    messagingSenderId: '147266380618',
    projectId: 'fir-login-signup-22aa1',
    storageBucket: 'fir-login-signup-22aa1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiHQjFBfgZPwqNHEtWh7PNUquqs4040hQ',
    appId: '1:147266380618:ios:6af70ec1e3128ec2c7d7b3',
    messagingSenderId: '147266380618',
    projectId: 'fir-login-signup-22aa1',
    storageBucket: 'fir-login-signup-22aa1.appspot.com',
    iosClientId: '147266380618-ss0mt8nu691srtcsnji4doq08o4qf564.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginSignupValidationFirebase',
  );
}
